[package]
name = "nac-generator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac_address = "1.1.3"
gethostname = "0.2.3"
sys-info = "0.9.1"
csv = "1.1.6"
chrono = "0.4.19"

